import pandas as pd
df=pd.read_csv(r"C:\Users\Admin\Downloads\archive\Student_Performance.csv")
df.head
df.info()
df.columns
df.isnull().sum()          
df.duplicated().sum()
df = df.drop_duplicates()
df.describe()
df.describe(include="O")
df.loc[:, "extra_activities"] = df["extra_activities"].map({"yes": 1, "no": 0})
df.loc[:, "internet_access"] = df["internet_access"].map({"yes": 1, "no": 0})
grouped_df=df.groupby("age")[["attendance_percentage","overall_score"]].mean()
grouped_df
grouped_df.plot(kind="bar",figsize=(9,5) , title="Average Attendance Percentage and Overall Score by Age")
plt.xlabel("Age")
plt.ylabel("Average Value")
plt.xticks(rotation=0)
plt.legend(title="Metric")
plt.show()
parent_education=df.groupby("parent_education")["overall_score"].mean().sort_values(ascending=False)
parent_education
parent_education.plot(kind="bar" , figsize=(8,5) , title="Average overall_score by parent_education" , color="#D2691E")
plt.xlabel("parent_education")
plt.ylabel("overall_score")
plt.xticks(rotation=45)
plt.show()
subject_avg = df[["math_score", "science_score", "english_score"]].mean().sort_values(ascending=False)
print(subject_avg)
plt.figure(figsize=(6,6))
plt.pie(subject_avg, labels=subject_avg.index, autopct='%1.1f%%', colors=["#FF9999","#66B3FF","#99FF99"], startangle=140)
plt.title("Proportion of Average Scores by Subject")
plt.show()
grade_counts = df["final_grade"].value_counts().sort_index()
print(grade_counts)
plt.figure(figsize=(6,6)) 
plt.pie(grade_counts, labels=grade_counts.index, autopct='%1.1f%%', colors=["#FFD700","#FF9999","#66B3FF","#99FF99","#FFB6C1","#D2691E"]) 
plt.title("Final Grade Distribution") 
plt.show()
